Homework4
lapatka-py/mipt_course_ap pull request #3
Opened 2020-09-29 14:03 UTC by lapatka-py

Готовы задачи 1-4

2020-10-03 08:17 UTC, lapatka-py commented
Готовы задачи 1-6 , по 7 вопрос

2020-10-05 17:49 UTC, alekseik1 requested changes
Не нужно удалять коды прошлых недель. Верни, пожалуйста.

Также оставил несколько комментов в коде. Исправь их и залей обновленную версию.

2020-10-05 17:49 UTC, alekseik1 commented on w1/коды.txt
> -извините, кодов нет
грустно, но да ладно

2020-10-05 17:49 UTC, alekseik1 commented on homework4/ex_3_w4.py
> +        print('Введите натуральное число')
Очень классно, что ты проверяешь входные данные на валидность!

2020-10-05 17:49 UTC, alekseik1 commented on homework4/ex_4_w4.py
> +if not namespace.file is None:
Тут можно заменить на `if namespace.file is not None`

2020-10-05 17:49 UTC, alekseik1 commented on homework4/ex_4_w4.py
> +                file.write(str(primes[i + 1]) + ' ')
В целом, хорошо, но лучше использовать пореже глобальные переменные

2020-10-05 17:49 UTC, alekseik1 commented on homework4/ex_6_w4.py
> +div(2, 4, show=True)
Лучше в конце файла с кодом оставлять пустую строку

2020-10-05 17:49 UTC, alekseik1 commented on homework4/ex_7_w4.py
> +def PATH(arg: str):
функции не стоит называть заглавными буквами

2020-10-05 17:49 UTC, alekseik1 commented on homework4/ex_7_w4.py
> +random_function(1, 1, 4, 5, arg=True, doka2= 'kill mind of little schoolars')
Хех, у меня отрицательное время выдал:
```bash
(base) ➜  homework4 git:(w4) python ex_7_w4.py
asd.txt
Мои аргументы 1 1 4 5
Мои ключи именованных аргументы arg doka2
-0.00011014938354492188 Mon Oct  5 20:47:57 2020 Mon Oct  5 20:47:57 2020 [1, 1, 4, 5] {'arg': True, 'doka2': 'kill mind of little schoolars'} -
```

2020-10-24 21:18 UTC, alekseik1 commented
Нет прогресса, поэтому считаю, что оценка устраивает. Закрываю PR

2020-10-24 21:18 UTC, merged